steps:
  - name: 'docker.io/library/python:3.8'
    id: Test
    entrypoint: /bin/sh
    args:
      - -c
      - 'export $(xargs < .env) &&
   export PYTHONPATH=.:src/plugins/ &&
   pip install pytest &&
   pip install -r requirements.txt &&
   pip install "apache-airflow[celery]==2.3.3" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.3.3/constraints-3.8.txt" &&
   pip install --upgrade pip &&
   pytest tests/*_test.py'
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy dags
    entrypoint: bash
    args: [ '-c', 'if [ "$BRANCH_NAME" == "dev" ]; then echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./src/dags gs://${_COMPOSER_BUCKET_DEV}/dags; elif [ "$BRANCH_NAME" == "hom" ]; then echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./src/dags gs://${_COMPOSER_BUCKET_HOM}/dags; else echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./src/dags gs://${_COMPOSER_BUCKET_PRD}/dags; fi']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy plugins
    entrypoint: bash
    args: [ '-c', 'if [ "$BRANCH_NAME" == "dev" ]; then echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./src/plugins gs://${_COMPOSER_BUCKET_DEV}/plugins; elif [ "$BRANCH_NAME" == "hom" ]; then echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./src/plugins gs://${_COMPOSER_BUCKET_HOM}/plugins; else echo "$BRANCH_NAME" && gsutil -m rsync -d -r ./src/plugins gs://${_COMPOSER_BUCKET_PRD}/plugins; fi']
substitutions:
  _COMPOSER_BUCKET_DEV: europe-west1-dp-orc-cmp-1-03b31633-bucket
  _COMPOSER_BUCKET_HOM: europe-west1-dp-orc-cmp-1-03b31633-bucket-hom
  _COMPOSER_BUCKET_PRD: europe-west1-dp-orc-cmp-1-03b31633-bucket-prd
options:
  logging: CLOUD_LOGGING_ONLY